name: Check PR Title
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  title-check:
    runs-on: ubuntu-latest
    steps:
      - name: print pr title
        run:  |
          echo toJSON(github.event.pull_request.title)
          echo ${{ contains(toJSON(github.event.pull_request.title), 'AB#')
          #${{ contains(toJSON(github.event.pull_request.title), 'AB#') == false }}
