name: Check PR Title
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches: main
jobs:
  title-check:
    runs-on: ubuntu-latest
    steps:
      - name: print pr title
        if: ${{ !contains(toJSON(github.event.pull_request.title), 'AB#') }}
        run: exit 1
