name: Check PR Title
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  
jobs:
  title-check:
    runs-on: ubuntu-latest
    steps:
      - name: print pr title
        if: ${{ contains(toJSON(github.event.pull_request.title), 'AB#') }}
        run: echo 'Hello'
